[workspace]
members = [
    "zee",
    "zee-grammar",
    "zee-highlight",
]

[profile.dev]
opt-level = 2

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
panic = "unwind"
strip = false
