[package]
name = "zee-grammar"
version = "0.1.0"
authors = ["Marius Cobzarenco <marius@reinfer.io>"]
edition = "2018"

[dependencies]
tree-sitter = "0.5.0"
lazy_static = "1.4.0"

[build-dependencies]
cc = "1.0.47"
tree-sitter = "0.5.0"
