[package]
name = "zee-highlight"
version = "0.1.0"
authors = ["Marius Cobzarenco <marius@reinfer.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
maplit = "1.0.2"
nom = "5.0.1"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
smallvec = { version = "1.0.0", features = ["serde"] }

zee-grammar = { path = "../grammar" }
tree-sitter = "0.5.0"
regex = "1.3.1"
serde_regex = "0.4.0"
fnv = "1.0.6"
